services:
  wppconnect-api:
    image: wppconnect/api:latest
    container_name: wppconnect_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=MinhaChaveSecreta123
      - PORT=8080
      - DB_TYPE=json            # Salva os dados localmente em arquivos JSON, sem precisar de Mongo
      - DB_HOST=localhost
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASS=secret
      - DB_BASE=wppconnect